#! /bin/bash
# Setup xsetwacom script for Intuos 3 9x12
# License: CC-0/Public-Domain license
# author: deevad

# Tablet definition
tabletstylus="HUION Huion Tablet stylus"
tabletpad="HUION Huion Tablet Pad pad"
touchpad="HUION Huion Tablet Touch Strip pad" #unsupported
dialpad="HUION Huion Tablet Dial pad" #unsupported
# Display all available option:
#xsetwacom get "$tabletstylus" all
#xsetwacom get "$tabletpad" all
#xsetwacom get "$touchpad" all
#xsetwacom get "$dialpad" all

# Reset
xsetwacom --set "$tabletstylus" ResetArea

# Map surface of the tablet to a monitor (in case of multiple)
# Note: get the name of the monitor with xrandr
# xsetwacom --set "$tabletstylus" MapToOutput "DisplayPort-0"

# Auto proportional Mapping:
# xsetwacom get "$tabletstylus" Area
# default: 0 0 50800 31750
# Enter under the resolution of your monitor:
screenX=2560
screenY=1440
Xtabletmaxarea=50800
Ytabletmaxarea=31750
areaY=$(( $screenY * $Xtabletmaxarea / $screenX ))
xsetwacom --set "$tabletstylus" Area 0 0 "$Xtabletmaxarea" "$areaY"
xsetwacom --set "$tabletstylus" Rotate half

# Stylus button:
#xsetwacom --set "$tabletstylus" Button 1 1 # default, to click and draw
#xsetwacom --set "$tabletstylus" Button 2 "key Control_L" # Ctrl = color picker
#xsetwacom --set "$tabletstylus" Button 3 3 # default (Right click)

# Tweaks
# Pressure curve:
xsetwacom --set "$tabletstylus" PressureCurve 0 0 100 100
# Softer
#xsetwacom --set "$tabletstylus" PressureCurve 0 10 40 85
# Configuration data trimming and suppression
# The event of this device are good; if you have CPU better to not filter
# them at operating system level to not loose any sensitivity.
# Minimal trimming is also good.
xsetwacom --set "$tabletstylus" Suppress 0 # data pt.s filtered, default is 2, 0-100
xsetwacom --set "$tabletstylus" RawSample 1 # data pt.s trimmed, default is 4, 1-20

# For left-handed mode (rotation):
#xsetwacom --set "$tabletstylus" Rotate half

# Buttons
# Note: touchpad around 10 button is not supported
#     +-----+
#     |  1  |
#     +-----+
#     |  2  |
#     +-----+
#     |  3  |
#     +-----+
#     |  8  |
#     +-----+
#     |  9  |
#     +-----+
# +---+-----+---+
# |             |
# |   +-----+   |
# |   | 10  |   |
# |   |     |   |
# |   +-----+   |
# |             |
# +---+-----+---+
#     +-----+
#     | 11  |
#     +-----+
#     | 12  |
#     +-----+
#     | 13  |
#     +-----+
#     | 14  |
#     +-----+
#     | 15  |
#     +-----+

# keyboard key for xsetwacom: https://pastebin.com/aXGDkJTU

xsetwacom --set "$tabletpad" Button 1 "key Control_L" # Ctrl = color picker
xsetwacom --set "$tabletpad" Button 2 "key KP_Divide" # / = Switch to previous used brush preset
xsetwacom --set "$tabletpad" Button 3 "key Shift_L" # Shift = Resize brush
xsetwacom --set "$tabletpad" Button 8 "key v" # v = line
xsetwacom --set "$tabletpad" Button 9 "key m" # m = mirror

xsetwacom --set "$tabletpad" Button 10 "key e" # e = eraser

xsetwacom --set "$tabletpad" Button 11 "key r" # r = pick layer
xsetwacom --set "$tabletpad" Button 12 "key l" # l = select lighter color
xsetwacom --set "$tabletpad" Button 13 "key k" # k = select darker color
xsetwacom --set "$tabletpad" Button 14 "key o" # o = more opacity
xsetwacom --set "$tabletpad" Button 15 "key i" # i = less opacity

echo "Gaomon Driver udpated !"
